### ISSUE TITLE
error that causes dada2 to terminate - my first time using the workflow so I may not have everything installed correctly

### ISSUE THREAD

**Issue by abooker10** [BigelowLab/edna-dada2#31]
Hi dada2 team-

Thank you for creating with workflow!
I am trying to use dada2 to analyze 18S PacBio data.
I edited the dada2_pacbio18S.yaml and job_submission.sh file to my specific locations on Charlie.

`#!/usr/bin/bash
#PBS -N run_dada2_pipeline
#PBS -q devel
#PBS -l ncpus=4,mem=5gb
#PBS -l walltime=2:00:00
#PBS -M abooker@bigelow.org
#PBS -m abe

module load dada2
data_path=/mnt/storage/labs/martinez_nfs/ECOHAB_Kb_virus/Data/PacBio/Kb_stocks_lysates_18S
Rscript $data_path"/dada2_pacbio.R" $data_path"/dada2_pacbio18S.yaml"
`

When I run the above script I get an error output 
`Error: unexpected '{' in:
"   # input basenames - so all we need to do is match
   fq_files <- sapply(names(fq_files){"
Execution halted`

Full error file attached.
[run_dada2_pipeline.e2671544.txt](https://github.com/BigelowLab/edna-dada2/files/13289910/run_dada2_pipeline.e2671544.txt)

Any suggestions on how to resolve the error?
Here is the edited yaml file I am using.
[dada2_pacbio18S.yaml.txt](https://github.com/BigelowLab/edna-dada2/files/13289917/dada2_pacbio18S.yaml.txt)

Thanks for any input,
Anne

**Comment by btupper** [comment]
Perhaps we should dial up a zoom session.  It's hard to discern what the issue is from the traceback of the error.

**Comment by abooker10** [comment]
A zoom session works for me. I can meet Wed (11/8) anytime before 11:15am and after 1pm.
Or I can meet Thursday (11/9) anytime before 1pm and after 3:30pm.

thank you!
Anne

**Comment by btupper** [comment]
Two issues - we need to add [compressr](https://github.com/BigelowLab/compressr) to generic package installs and there is a block structure [issue](https://github.com/BigelowLab/edna-dada2/issues/32)
