### ISSUE TITLE
incomplete preprocess run for PacBio 18S sequences

### ISSUE THREAD

**Issue by abooker10** [BigelowLab/edna-dada2#33]
Hi dada2 team-

I am running into an issue getting the preprocessing step to work for pacbio 18s data. I am following the instructions here: https://github.com/BigelowLab/edna-dada2/wiki/Processing-PacBio-reads

I think my preprocess run was a partial success because a filter_and_trim.csv was generated, but I did not get a truncLen.csv which is required for the post processing step.

I am attaching all my files because I am not sure what direction to go in to remedy this.
job_submission.sh
[job_submission.sh.txt](https://github.com/BigelowLab/edna-dada2/files/13309472/job_submission.sh.txt)

the preprocess yaml file - *I had to edit the filtering min and max in this file to accommodate my samples*
[pacbio_preprocess.yaml.txt](https://github.com/BigelowLab/edna-dada2/files/13309487/pacbio_preprocess.yaml.txt)

the preprocess R file
[pacbio_preprocess.R.txt](https://github.com/BigelowLab/edna-dada2/files/13309492/pacbio_preprocess.R.txt)

the post process yaml - I did not edit this file
[pacbio_postprocess.yaml.txt](https://github.com/BigelowLab/edna-dada2/files/13309515/pacbio_postprocess.yaml.txt)

the error and output files from the run
[run_dada2_pipeline.o2671568.txt](https://github.com/BigelowLab/edna-dada2/files/13309524/run_dada2_pipeline.o2671568.txt)
[run_dada2_pipeline.e2671568.txt](https://github.com/BigelowLab/edna-dada2/files/13309525/run_dada2_pipeline.e2671568.txt)

the Log file from the preprocess run
[log.txt](https://github.com/BigelowLab/edna-dada2/files/13309549/log.txt)

the audit file from the preprocess run
[audit.txt](https://github.com/BigelowLab/edna-dada2/files/13309553/audit.txt)

Thanks for any advice on how to get the truncLen.csv file generated during the preprocess run.

Sincerely,
Anne

**Comment by abooker10** [comment]
Hi Robin-
It worked with the truncLen file!
Thank you, and apologies I did not try that on my own.
Anne

**Comment by btupper** [comment]
@robinsleith @abooker10 Can we close this?

**Comment by abooker10** [comment]
In my understanding we can, thanks for all the help!

Anne
